#!/bin/bash

#Root access
# echo -e "PASSWORD" | enable

# Commands outputs in variables
OUTPUTCPU=pwd
OUTPUTMEMORY=ls
# OUTPUTVPN=l

# Create and write commands results into a txt file
$OUTPUTCPU > server-stats.txt
$OUTPUTMEMORY >> server-stats.txt
# OUTPUTVPN >> server-stats.txt


# HTML to e-mail
{
  echo "<!DOCTYPE html>"
  echo "<html lang="en">"
  echo "<head>"
  echo "<style type=\"text/css\">"
  echo ".container-table100 {"
  echo "  width: 100%;"
  echo "  min-height: 100vh;"
  echo ""
  echo "  align-items: center;"
  echo "  justify-content: center;"
  echo "  flex-wrap: wrap;"
  echo "}"
  echo ""
  echo ".wrap-table100 {"
  echo "  width: 500px;"
  echo "}"
  echo ""
  echo "table {"
  echo "  border-spacing: 1;"
  echo "  border-collapse: collapse;"
  echo "  background: white;"
  echo "  border-radius: 10px;"
  echo "  overflow: hidden;"
  echo "  width: 100%;"
  echo "  margin: 0 auto;"
  echo "}"
  echo "table td, table th {"
  echo "  padding-left: 8px;"
  echo "}"
  echo "table thead tr {"
  echo "  height: 45px;"
  echo "  background: #36304a;"
  echo "}"
  echo "table tbody tr {"
  echo "  height: 35px;"
  echo "}"
  echo "table tbody tr:last-child {"
  echo "  border: 0;"
  echo "}"
  echo "table td, table th {"
  echo "  text-align: left;"
  echo "}"
  echo "table td.l, table th.l {"
  echo "  text-align: right;"
  echo "}"
  echo "table td.c, table th.c {"
  echo "  text-align: center;"
  echo "}"
  echo "table td.r, table th.r {"
  echo "  text-align: center;"
  echo "}"
  echo ""
  echo ""
  echo ".table100-head th{"
  echo "  font-family: OpenSans-Regular;"
  echo "  font-size: 14px;"
  echo "  color: #fff;"
  echo "  line-height: 1.2;"
  echo "  font-weight: unset;"
  echo "}"
  echo ""
  echo "tbody tr:nth-child(even) {"
  echo "  background-color: #f5f5f5;"
  echo "}"
  echo ""
  echo "tbody tr {"
  echo "  font-family: OpenSans-Regular;"
  echo "  font-size: 12px;"
  echo "  color: #808080;"
  echo "  line-height: 1.2;"
  echo "  font-weight: unset;"
  echo "}"
  echo ""
  echo "tbody tr:hover {"
  echo "  color: #555555;"
  echo "  background-color: #f5f5f5;"
  echo "  cursor: pointer;"
  echo "}"
  echo ""
  echo ".column1 {"
  echo "  width: 260px;"
  echo "  padding-left: 40px;"
  echo "}"
  echo ""
  echo ".column2 {"
  echo "  width: 160px;"
  echo "}"
  echo ""
  echo ".column3 {"
  echo "  width: 245px;"
  echo "}"
  echo ""
  echo ".column4 {"
  echo "  width: 110px;"
  echo "  text-align: right;"
  echo "}"
  echo ""
  echo ".column5 {"
  echo "  width: 170px;"
  echo "  text-align: right;"
  echo "}"
  echo ""
  echo ".column6 {"
  echo "  width: 222px;"
  echo "  text-align: right;"
  echo "  padding-right: 62px;"
  echo "}"
  echo ".column7 {"
  # echo "  width: 222px;"
  echo "  text-align: center;"
  echo "  font-family: OpenSans-Regular;"
  echo "  font-size: 18px;"
  echo "  color: #fff;"
  echo "  line-height: 1.2;"
  echo "  font-weight: unset;"
  echo "}"
  echo ""
  echo ""
  echo "@media screen and (max-width: 992px) {"
  echo "  table {"
  echo "    display: block;"
  echo "  }"
  echo "  table > *, table tr, table td, table th {"
  echo "    display: block;"
  echo "  }"
  echo "  table thead {"
  echo "    display: none;"
  echo "  }"
  echo "  table tbody tr {"
  echo "    height: auto;"
  echo "    padding: 37px 0;"
  echo "  }"
  echo "  table tbody tr td {"
  echo "    padding-left: 40% !important;"
  echo "    margin-bottom: 24px;"
  echo "  }"
  echo "  table tbody tr td:last-child {"
  echo "    margin-bottom: 0;"
  echo "  }"
  echo "  table tbody tr td:before {"
  echo "    font-family: OpenSans-Regular;"
  echo "    font-size: 14px;"
  echo "    color: #999999;"
  echo "    line-height: 1.2;"
  echo "    font-weight: unset;"
  echo "    position: absolute;"
  echo "    width: 40%;"
  echo "    left: 30px;"
  echo "    top: 0;"
  echo "  }"
  echo ""
  echo "  .column4,"
  echo "  .column5,"
  echo "  .column6 {"
  echo "    text-align: left;"
  echo "  }"
  echo ""
  echo "  .column4,"
  echo "  .column5,"
  echo "  .column6,"
  echo "  .column1,"
  echo "  .column2,"
  echo "  .column3 {"
  echo "    width: 100%;"
  echo "  }"
  echo ""
  echo "  tbody tr {"
  echo "    font-size: 14px;"
  echo "  }"
  echo "}"
  echo ""
  echo "@media (max-width: 576px) {"
  echo "  .container-table100 {"
  echo "    padding-left: 15px;"
  echo "    padding-right: 15px;"
  echo "  }"
  echo "}"
  echo "</style>"
  echo "	<title>CPU / Memory / VPN stats</title>"
  echo "	<meta charset="UTF-8">"
  echo "	<meta name="viewport" content="width=device-width, initial-scale=1">"
  echo "<!--===============================================================================================-->"
  echo "</head>"
  echo "<body>"
  echo	"<p>Prezados, <br/><br/> Segue os dados do monitoramento atual dos Firewalls de VPN.</p>"
  echo	"<ul>"
  echo	"	<li>show cpu</li>"
  echo	"	<li>show mem</li>"
  echo	"	<li>show vpn-sessiondb det</li>"
  echo	"</ul>"
  echo "	<div class="limiter">"
  echo "		<div class="container-table100">"
  echo "			<div class="wrap-table100">"
  echo "				<div class="table100">"
  echo "					<table>"
  echo "						<thead>"
  echo "							<tr class="table100-head">"
  echo "								<th class="column1">Horario</th>"
  echo "								<th class="column2">CPU %</th>"
  echo "								<th class="column3">Memória %</th>"
  echo "								<th class="column4">VPNs Ativas</th>"
  echo "								<th class="column6">Status</th>"
  echo "							</tr>"
  echo "						</thead>"
  echo "						<tbody>"
  echo "								<tr>"
  echo "									<td class="column1">9:00</td>"
  echo "									<td class="column2">1</td>"
  echo "									<td class="column3">1</td>"
  echo "									<td class="column4">15</td>"
  echo "									<td class="column6">OK</td>"
  echo "								</tr>"
  echo "								<tr>"
  echo "									<td class="column1">11:00</td>"
  echo "									<td class="column2">1</td>"
  echo "									<td class="column3">1</td>"
  echo "									<td class="column4">15</td>"
  echo "									<td class="column6">OK</td>"
  echo "								</tr>"
  echo "								<tr>"
  echo "									<td class="column1">13:00</td>"
  echo "									<td class="column2">1</td>"
  echo "									<td class="column3">1</td>"
  echo "									<td class="column4">15</td>"
  echo "									<td class="column6">OK</td>"
  echo "								</tr>"
  echo "								<tr>"
  echo "									<td class="column1">15:00</td>"
  echo "									<td class="column2">1</td>"
  echo "									<td class="column3">1</td>"
  echo "									<td class="column4">15</td>"
  echo "									<td class="column6">OK</td>"
  echo "								</tr>"
  echo "								<tr>"
  echo "									<td class="column1">17:00</td>"
  echo "									<td class="column2">1</td>"
  echo "									<td class="column3">1</td>"
  echo "									<td class="column4">15</td>"
  echo "									<td class="column6">OK</td>"
  echo "								</tr>"
  echo "								<tr>"
  echo "									<td class="column1">19:00</td>"
  echo "									<td class="column2">1</td>"
  echo "									<td class="column3">1</td>"
  echo "									<td class="column4">15</td>"
  echo "									<td class="column6">OK</td>"
  echo "								</tr>"
  echo "								<tr>"
  echo "									<td colspan=5 class="column7"><b>Legenda de Utilização</b></td>"
  echo "								</tr>"
  echo "						</tbody>"
  echo "					</table>"
  echo "				</div>"
  echo "			</div>"
  echo "		</div>"
  echo "	</div>"
  echo "</body>"
  echo "</html>"
} > e-mail.html
